# Generated by Django 6.0.8 on 2026-09-10 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=120)),
                ('grade', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=80)),
                ('medium', models.CharField(max_length=80)),
                ('version', models.CharField(default='2026', max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['board', 'grade', 'subject', 'medium'],
                'constraints': [models.UniqueConstraint(fields=('board', 'grade', 'subject', 'medium', 'version'), name='unique_curriculum_version')],
            },
        ),
        migrations.CreateModel(
            name='ConceptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial overlap'), ('missing', 'Missing from source')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('rationale', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('destination_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_mappings', to='map.concept')),
                ('source_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='map.concept')),
                ('destination_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mappings', to='map.curriculum')),
                ('source_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_mappings', to='map.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=8)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_items', to='map.concept')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_items', to='map.curriculum')),
            ],
            options={
                'ordering': ['concept', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Teacher review'), ('complete', 'Complete')], default='active', max_length=16)),
                ('max_questions', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targeted_sessions', to='map.concept')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BridgePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('complete', 'Complete')], default='draft', max_length=16)),
                ('teacher_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_plan', to='map.diagnosticsession')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('preferred_language', models.CharField(default='hi', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_learners', to='map.curriculum')),
                ('source_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_learners', to='map.curriculum')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to='map.learnerprofile'),
        ),
        migrations.CreateModel(
            name='BridgeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('activity', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('evidence_prompt', models.TextField(blank=True)),
                ('resource_url', models.URLField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='map.bridgeplan')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.concept')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'concept'), name='unique_concept_per_plan'), models.UniqueConstraint(fields=('plan', 'order'), name='unique_order_per_plan')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_term', models.CharField(blank=True, max_length=160)),
                ('learning_outcome', models.TextField(blank=True)),
                ('coverage_depth', models.PositiveSmallIntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='map.concept')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_concepts', to='map.curriculum')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'concept'), name='unique_concept_per_curriculum')],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.diagnosticitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='map.diagnosticsession')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'item'), name='one_attempt_per_item')],
            },
        ),
        migrations.CreateModel(
            name='PrerequisiteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_edges', to='map.curriculum')),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requires_concepts', to='map.concept')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports_concepts', to='map.concept')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'prerequisite', 'dependent'), name='unique_prerequisite_edge')],
            },
        ),
    ]
