# Generated by Django 6.0.8 on 2026-09-10 19:26

from django.db import migrations, models

import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=map.models.create_support_reference, editable=False, max_length=16, unique=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('requester_role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent or guardian'), ('educator', 'Educator or counsellor')], default='student', max_length=20)),
                ('category', models.CharField(choices=[('school-change', 'School or board change'), ('language', 'Language difficulty'), ('learning-break', 'Learning interruption'), ('higher-education', 'College or programme change'), ('study-abroad', 'Study-abroad preparation'), ('unsure', 'Not yet classified')], max_length=32)),
                ('summary', models.TextField()),
                ('source_label', models.CharField(blank=True, max_length=180)),
                ('source_location', models.CharField(blank=True, max_length=100)),
                ('destination_label', models.CharField(blank=True, max_length=180)),
                ('destination_location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Request received'), ('evidence_review', 'Evidence review'), ('gap_analysis', 'Gap comparison'), ('roadmap', 'Support roadmap'), ('readiness_review', 'Readiness review')], default='received', max_length=24)),
                ('progress_stage', models.PositiveSmallIntegerField(default=1)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
