# Generated by Django 6.0.8 on 2026-09-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_supportcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('education_level', models.CharField(choices=[('school', 'School'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('professional', 'Professional or regulated')], max_length=20)),
                ('case_type', models.CharField(max_length=60)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('boundary', 'Guardrail boundary')], default='common', max_length=16)),
                ('learner', models.JSONField(default=dict)),
                ('source_program', models.JSONField(default=dict)),
                ('destination_program', models.JSONField(default=dict)),
                ('learner_evidence', models.JSONField(default=list)),
                ('destination_requirements', models.JSONField(default=list)),
                ('expected_results', models.JSONField(default=list)),
                ('expected_roadmap', models.JSONField(default=list)),
                ('source_documents', models.JSONField(default=list)),
                ('guardrails', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('synthetic_fields', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('reviewed_demo', 'Reviewed demonstration'), ('team_review', 'Team review required'), ('source_review', 'Official source review required'), ('illustrative', 'Illustrative only')], default='team_review', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scenario_id'],
            },
        ),
    ]
