# Generated by Django 6.0.8 on 2026-09-11 03:00

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def enable_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0003_transitionscenario"),
    ]

    operations = [
        migrations.RunPython(enable_vector_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name="AcademicSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=240)),
                ("organisation", models.CharField(blank=True, max_length=180)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official_pdf", "Official PDF"),
                            ("official_webpage", "Official webpage"),
                            ("reviewed_fixture", "Reviewed fixture"),
                            ("synthetic_fixture", "Synthetic demonstration fixture"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("version", models.CharField(blank=True, max_length=80)),
                ("retrieved_at", models.DateField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("illustrative", "Illustrative only"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["source_id"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_id", models.CharField(max_length=140, unique=True)),
                ("section", models.CharField(blank=True, max_length=180)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("text", models.TextField()),
                ("canonical_terms", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                ("embedding_model", models.CharField(blank=True, max_length=180)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_chunks",
                        to="map.transitionscenario",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="map.academicsource",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_id"],
                "indexes": [
                    models.Index(
                        fields=["scenario", "approved"],
                        name="map_evidenc_scenari_09de37_idx",
                    ),
                    models.Index(
                        fields=["source", "approved"],
                        name="map_evidenc_source__8fdddf_idx",
                    ),
                ],
            },
        ),
    ]
