# Generated by Django 6.0.8 on 2026-09-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0005_evidence_embedding_hnsw"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportcase",
            name="analysed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="analysis_confidence_level",
            field=models.CharField(
                choices=[
                    ("not_analysed", "Not analysed"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="not_analysed",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="analysis_confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="analysis_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="matched_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_support_cases",
                to="map.transitionscenario",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="review_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="review_route",
            field=models.CharField(
                choices=[
                    ("not_routed", "Not routed"),
                    ("provisional_guidance", "Provisional guidance"),
                    ("instructor_review", "Instructor review"),
                    ("specialist_escalation", "Specialist escalation"),
                ],
                default="not_routed",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="supportcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Request received"),
                    ("evidence_review", "Evidence review"),
                    ("gap_analysis", "Gap comparison"),
                    ("roadmap", "Support roadmap"),
                    ("readiness_review", "Readiness review"),
                    ("instructor_review", "Instructor review"),
                ],
                default="received",
                max_length=24,
            ),
        ),
    ]
